function [M1hr,M2hr,M3hr,M1s,M2s,M3s,M1l,M2l,M3l,M1pr,M2pr,M3pr]=PETHSpindlesRipplesML(res)

% inputs:
% res (optional) = directory

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% INITIATE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~exist('res','var')
    res=pwd;
end

infoDepth={'Sup','Deep'};
structureName={'PFCx'};%,'PaCx'};

scrsz = get(0,'ScreenSize');
disp(' ')
disp(res)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% %%%%%%%%%%%%%%%%%%%% LOADING HIPPOCAMPAL LFPs %%%%%%%%%%%%%%%%%%%%%%%%%%

eval('tempload=load([res,''/LFPData/InfoLFP.mat''],''InfoLFP'');')
chHPC=tempload.InfoLFP.channel(find(strcmp(tempload.InfoLFP.structure,'dHPC')));

if ~isempty(chHPC)
    
    % loading ripples generated by FindRipplesKarimSB.m
    %disp('   Loading RipplesdHPC.mat')
    %eval('tempload=load([res,''/RipplesdHPC.mat''],''dHPCrip'',''chHPC'');')
    disp('   Loading RipplesdHPC52.mat  (!!! change by ML on 03/10/2015)')
    eval('tempload=load([res,''/RipplesdHPC25.mat''],''dHPCrip'',''chHPC'');')
    Rip=tempload.dHPCrip;
    
    numChRip=find(chHPC==tempload.chHPC);
    % loading LFPs
    for hpc=1:length(chHPC)
        clear temploadLFP
        disp(['   Loading LFP',num2str(chHPC(hpc)),'.mat (Hippocampus channel ',num2str(hpc),')...'])
        eval(['temploadLFP=load([res,''/LFPData/LFP',num2str(chHPC(hpc)),'.mat''],''LFP'');'])
        LFPhpc{hpc}=temploadLFP.LFP;
    end
    
    % Construct matrices
    M1hr=PlotRipRaw(LFPhpc{1},Rip(:,2),80); close
    try M2hr=PlotRipRaw(LFPhpc{2},Rip(:,2),80); close; catch, M2hr=[]; end
    try M3hr=PlotRipRaw(LFPhpc{3},Rip(:,2),80); close; catch, M3hr=[]; end

else
    disp('   No HPC channel !!!')
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% %%%%%%%%%%%%%%%%%%%%%% LOADING CORTICAL LFPs %%%%%%%%%%%%%%%%%%%%%%%%%%%

MSpindles={};

% loading ripples generated by FindRipplesKarimSB.m
for nn=1:length(structureName)
    
    eval('tempload=load([res,''/LFPData/InfoLFP.mat''],''InfoLFP'');')
    chCTX=tempload.InfoLFP.channel(find(strcmp(tempload.InfoLFP.structure,structureName{nn})));
    savechCTX{nn}=chCTX;
        % loading LFPs
        
        for ctx=1:length(chCTX)
            clear temploadLFP
            disp(['   Loading LFP',num2str(chCTX(ctx)),'.mat (',structureName{nn},' channel ',num2str(ctx),')...'])
            eval(['temploadLFP=load([res,''/LFPData/LFP',num2str(chCTX(ctx)),'.mat''],''LFP'');'])
            LFPctx{ctx}=temploadLFP.LFP;
        end
        
        % Ripples
        try M1pr=PlotRipRaw(LFPctx{1},Rip(:,2),500);close; catch, M1pr=[]; end
        try M2pr=PlotRipRaw(LFPctx{2},Rip(:,2),500);close; catch, M2pr=[]; end
        try M3pr=PlotRipRaw(LFPctx{3},Rip(:,2),500);close; catch, M3pr=[]; end
        MCtxOnRip{nn}={M1pr M2pr M3pr};
        
        for id=1:length(infoDepth)
            clear tempload SpiH SpiL
            disp(['   Loading Spindles',structureName{nn},infoDepth{id},'.mat'])
            try
                eval(['tempload=load([res,''/Spindles',structureName{nn},infoDepth{id},'.mat''],''SpiLow'',''SpiHigh'');'])
                SpiH=tempload.SpiHigh;
                SpiL=tempload.SpiLow;
            catch
                disp(' -> problem')
            end
            % Construct matrices
            % high Spindles
            try M1s=PlotRipRaw(LFPctx{1},SpiH(:,2),500);close; catch, M1s=[]; end
            try M2s=PlotRipRaw(LFPctx{2},SpiH(:,2),500);close; catch, M2s=[]; end
            try M3s=PlotRipRaw(LFPctx{3},SpiH(:,2),500);close; catch, M3s=[]; end
            % low Spindles
            try M1l=PlotRipRaw(LFPctx{1},SpiL(:,2),500);close; catch, M1l=[]; end
            try M2l=PlotRipRaw(LFPctx{2},SpiL(:,2),500);close; catch, M2l=[]; end
            try M3l=PlotRipRaw(LFPctx{3},SpiL(:,2),500);close; catch, M3l=[]; end
            
            MSpindles{nn,id}={M1s M2s M3s ; M1l M2l M3l};
        end
    
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% FINAL DISPLAY %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


figure('color',[1 1 1],'Position',scrsz),

% Hippocampal LFPs on Ripples events
subplot(4,3,1), hold on,
try plot(M1hr(:,1),M1hr(:,2),'k','LineWidth',linew(1)); end
try plot(M1hr(:,1),M2hr(:,2),'b','LineWidth',linew(2)); end
try plot(M1hr(:,1),M3hr(:,2),'r','LineWidth',linew(3)); end
title('Hippocampal LFPs on Ripples events')
line([0 0],ylim,'Color',[0.5 0.5 0.5])
xlabel('Time (s)')
text(0,min(ylim)+diff(ylim)*1.25,res)

% re Hippocampal LFPs on Ripples events
subplot(4,3,10), hold on,
leg=[];
linew=[1 1 1]; linew(numChRip)=2;
ChRipLeg={'','',''}; ChRipLeg{numChRip}=' (detection)';
try plot(M1hr(:,1),M1hr(:,2),'k','LineWidth',linew(1)); leg=[leg,{['Ch ',num2str(chHPC(1)),ChRipLeg{1}]}];end
try plot(M1hr(:,1),M2hr(:,2),'b','LineWidth',linew(2)); leg=[leg,{['Ch ',num2str(chHPC(2)),ChRipLeg{2}]}];end
try plot(M1hr(:,1),M3hr(:,2),'r','LineWidth',linew(3)); leg=[leg,{['Ch ',num2str(chHPC(3)),ChRipLeg{3}]}];end
title('Hippocampal LFPs on Ripples events')
line([0 0],ylim,'Color',[0.5 0.5 0.5])
xlabel('Time (s)')
legend(leg)

% Cortical LFPs on Ripples event
subplot(4,3,4), hold on,
leg=[];
tempM=MCtxOnRip{1};
M1pr=tempM{1};
M2pr=tempM{2};
M3pr=tempM{3};
try plot(M1pr(:,1),M1pr(:,2),'k');leg=[leg,{['Ch ',num2str(savechCTX{1}(1))]}];end
try plot(M1pr(:,1),M2pr(:,2),'b');leg=[leg,{['Ch ',num2str(savechCTX{1}(2))]}];end
try plot(M1pr(:,1),M3pr(:,2),'r');leg=[leg,{['Ch ',num2str(savechCTX{1}(3))]}];end
title([structureName{1},' LFPs on Ripples events'])
line([0 0],ylim,'Color',[0.5 0.5 0.5])
xlabel('Time (s)')
legend(leg)

% Cortical LFPs on Ripples event
subplot(4,3,7), hold on,
leg=[];
tempM=MCtxOnRip{2};
M1pr=tempM{1};
M2pr=tempM{2};
M3pr=tempM{3};
try plot(M1pr(:,1),M1pr(:,2),'k');leg=[leg,{['Ch ',num2str(savechCTX{2}(1))]}];end
try plot(M1pr(:,1),M2pr(:,2),'b');leg=[leg,{['Ch ',num2str(savechCTX{2}(2))]}];end
try plot(M1pr(:,1),M3pr(:,2),'r');leg=[leg,{['Ch ',num2str(savechCTX{2}(3))]}];end
title([structureName{2},' LFPs on Ripples events'])
line([0 0],ylim,'Color',[0.5 0.5 0.5])
xlabel('Time (s)')
legend(leg)


for nn=1:length(structureName)
    for id=1:length(infoDepth)
        
        clear tempM M1s M2s M3s M1l M2l M3l 
        tempM=MSpindles{nn,id};
        M1s=tempM{1,1};
        M2s=tempM{1,2};
        M3s=tempM{1,3};
        M1l=tempM{2,1};
        M2l=tempM{2,2};
        M3l=tempM{2,3};
        
        % Cortical LFPs on High Spindles events
        subplot(4,3,6*(nn-1)+1+id), hold on,
        leg=[];
        try plot(M1s(:,1),M1s(:,2),'k'); leg=[leg,{['Ch ',num2str(savechCTX{nn}(1))]}];end
        try plot(M1s(:,1),M2s(:,2),'b'); leg=[leg,{['Ch ',num2str(savechCTX{nn}(2))]}];end
        try plot(M1s(:,1),M3s(:,2),'r'); leg=[leg,{['Ch ',num2str(savechCTX{nn}(3))]}];end
        title(['Cortical LFPs on High ',structureName{nn},infoDepth{id},'Spindles events'])
        line([0 0],ylim,'Color',[0.5 0.5 0.5])
        xlabel('Time (s)')
        legend(leg)
        
        % Cortical LFPs on Low 'Spindles events
        subplot(4,3,6*(nn-1)+4+id), hold on,
        leg=[];
        try plot(M1l(:,1),M1l(:,2),'k'); leg=[leg,{['Ch ',num2str(savechCTX{nn}(1))]}];end
        try plot(M1l(:,1),M2l(:,2),'b'); leg=[leg,{['Ch ',num2str(savechCTX{nn}(2))]}];end
        try plot(M1l(:,1),M3l(:,2),'r'); leg=[leg,{['Ch ',num2str(savechCTX{nn}(3))]}];end
        title(['Cortical LFPs on Low ',structureName{nn},infoDepth{id},'Spindles events'])
        line([0 0],ylim,'Color',[0.5 0.5 0.5])
        xlabel('Time (s)')
        legend(leg)
    end
end
    