function guireg_fig=OnlineGuiReglage(FigName)
% function guireg_fig=OnlineGuiReglage(obj,event);
% let online control of paramteres for image treatments

color_on = [0 0 0];
global BW_threshold smaller_object_size sm_fact strsz SrdZone se
global guireg_fig

typical_size=300;
MaxSmoothFact=20;
maxsrtsz=20;
maxsrndsz=80;

% create figure
guireg_fig=figure('units','normalized',...
    'position',[0.1 0.1 0.4 0.6],...
    'numbertitle','off',...
    'name','Online Mouse Tracking : Setting Parameters',...
    'menubar','none',...
    'tag','figure reglage');
set(guireg_fig,'Color',color_on);

% create names of sliders
text1=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.05 0.85 0.10 0.05],...
    'string','threshold');

text2=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.25 0.85 0.10 0.05],...
    'string','min size');

text3=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.45 0.85 0.10 0.05],...
    'string','erode obj size');

text4=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.65 0.85 0.10 0.05],...
    'string','Fz Srnd Sz');

text5=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.85 0.85 0.10 0.05],...
    'string','smoothing');

% create sliders
slider_threshold = uicontrol(guireg_fig,'style','slider',...
    'units','normalized',...
    'position',[0.06 0.1 0.08 0.7],...
    'callback', @threshold);
set(slider_threshold,'Value',BW_threshold);

slider_small=uicontrol(guireg_fig,'style','slider',...
    'units','normalized',...
    'position',[0.26 0.1 0.08 0.7],...
    'callback', @elimination);
set(slider_small,'Value',smaller_object_size/typical_size);

slider_strel = uicontrol(guireg_fig,'style','slider',...
    'units','normalized',...
    'position',[0.46 0.1 0.08 0.7],...
    'callback', @setstrelsize);
set(slider_strel,'Value',strsz/maxsrtsz);

slider_srndsz = uicontrol(guireg_fig,'style','slider',...
    'units','normalized',...
    'position',[0.66 0.1 0.08 0.7],...
    'callback', @setsrndsz);
set(slider_srndsz,'Value',SrdZone/maxsrndsz);

slider_smoothing = uicontrol(guireg_fig,'style','slider',...
    'units','normalized',...
    'position',[0.86 0.1 0.08 0.7],...
    'callback', @setsmoothval);
set(slider_smoothing,'Value',sm_fact/MaxSmoothFact);

% create labels with actual values
text6=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.06 0.05 0.08 0.03],...
    'string',num2str(BW_threshold));

text7=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.26 0.05 0.08 0.03],...
    'string',num2str(smaller_object_size));

text8=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.46 0.05 0.08 0.03],...
    'string',num2str(strsz));

text9=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.66 0.05 0.08 0.03],...
    'string',num2str(SrdZone));

text10=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.86 0.05 0.08 0.03],...
    'string',num2str(sm_fact));

%get threshold value
    function threshold(obj,event)
        BW_threshold = get(slider_threshold, 'value');
        set(text6,'string',num2str(BW_threshold))
    end

%get min object size
    function elimination(obj,event)
        smaller_object_size = round(get(slider_small,'value')*typical_size);
        set(text7,'string',num2str(smaller_object_size))
    end

%get object size for erosion
    function setstrelsize(~,~)
        strsz = round(get(slider_strel,'value')*maxsrtsz);
        se = strel('disk',strsz);
        set(text8,'string',num2str(strsz));
    end

%get surround zone size
    function setsrndsz(~,~)
        SrdZone = round(get(slider_srndsz,'value')*maxsrndsz);
        set(text9,'string',num2str(SrdZone));
    end

%get surround zone size
    function setsmoothval(~,~)
        sm_fact = round(get(slider_smoothing,'value')*MaxSmoothFact);
        set(text10,'string',num2str(sm_fact));
    end
end
