function [cf_,good_]=LinearFit(X,Y1)
%CREATEFIT Create plot of data sets and fits
%   CREATEFIT(X,Y1,Y2,Y3)
%   Creates a plot, similar to the plot in the main Curve Fitting Tool,
%   using the data that you provide as input.  You can
%   use this function with the same data you used with CFTOOL
%   or with different data.  You may want to edit the function to
%   customize the code and this help message.
%
%   Number of data sets:  1
%   Number of fits:  1


% Auto-generated by MATLAB on 25-Jul-2014 10:53:05


% --- Plot data that was originally in data set "Y1 vs. X"
X = X(:);
Y1 = Y1(:);


% --- Create fit "fit 1"
ok_ = isfinite(X) & isfinite(Y1);
if ~all( ok_ )
    warning( 'GenerateMFile:IgnoringNansAndInfs',...
        'Ignoring NaNs and Infs in data.' );
end
ft_ = fittype('poly1');

% Fit this model using new data
[cf_,good_] = fit(X(ok_),Y1(ok_),ft_);
% Alternatively uncomment the following lines to use coefficients from the
% original fit. You can use this choice to plot the original fit against new
% data.
%    cv_ = { -2.5722643763440773412, 538.95156411932691753};
%    cf_ = cfit(ft_,cv_{:});

