function guireg_fig=OnlineGuiReglage(obj,event);

% function guireg_fig=OnlineGuiReglage(obj,event);
% let online control of paramteres for image treatments

global BW_threshold2
global smaller_object_size2
global shape_ratio2

color_on = [ 0 0 0];
if ~exist('typical_size','var'), typical_size=300;end
typical_rapport=10;

guireg_fig=figure('units','normalized',...
    'position',[0.1 0.1 0.15 0.6],...
    'numbertitle','off',...
    'name','Online Mouse Tracking : Setting Parameters',...
    'menubar','none',...
    'tag','figure reglage');
set(guireg_fig,'Color',color_on);

hand(2)=uicontrol(guireg_fig,'style','pushbutton',...
    'units','normalized',...
    'position',[0.01 0.9 0.8 0.05],...
    'string','Stop for Manual Inputs',...
    'tag','init',...
    'callback', @enterManual);

text1=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.05 0.85 0.25 0.03],...
    'string','seuil couleur');

text2=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.4 0.85 0.25 0.03],...
    'string','seuil objets');

text3=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.7 0.85 0.25 0.03],...
    'string','rapport axes');

slider_seuil = uicontrol(guireg_fig,'style','slider',...
    'units','normalized',...
    'position',[0.05 0.1 0.15 0.7],...
    'callback', @seuil);
    set(slider_seuil,'Value',BW_threshold2);
    
slider_small=uicontrol(guireg_fig,'style','slider',...
    'units','normalized',...
    'position',[0.4 0.1 0.15 0.7],...
    'callback', @elimination);
    set(slider_small,'Value',smaller_object_size2/typical_size);

slider_rapport = uicontrol(guireg_fig,'style','slider',...
    'units','normalized',...
    'position',[0.7 0.1 0.15 0.7],...
    'callback', @rapport);
    set(slider_rapport,'Value',shape_ratio2/typical_rapport);


text5=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.05 0.05 0.25 0.03],...
    'string',num2str(BW_threshold2));


text6=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.4 0.05 0.25 0.03],...
    'string',num2str(smaller_object_size2));


text4=uicontrol(guireg_fig,'style','text', ...
    'units','normalized',...
    'position',[0.7 0.05 0.25 0.03],...
    'string',num2str(shape_ratio2));



    function seuil(obj,event)
        
        BW_threshold2 = get(slider_seuil, 'value');
        set(text5,'string',num2str(BW_threshold2))
        disp([' New BW_threshold=',num2str(BW_threshold2)])
    end
%get threshold value
    function elimination(obj,event)
        smaller_object_size2 = round(get(slider_small,'value')*typical_size);
        set(text6,'string',num2str(smaller_object_size2))
        disp(['   New smaller_object_size=',num2str(smaller_object_size2)])
    end
    function rapport(obj,event)
        shape_ratio2 = (get(slider_rapport,'value')*typical_rapport);
        set(text4,'string',num2str(shape_ratio2))
        disp(['     New shape_ratio=',num2str(shape_ratio2)])
    end

    function enterManual(obj,event)
        defAns={num2str(BW_threshold2) num2str(smaller_object_size2) num2str(shape_ratio2)};
        prompt = {'BW_threshold','smaller_object_size','shape_ratio'};
        dlg_title = 'Change parameters for offline tracking:';
        answer = inputdlg(prompt,dlg_title,1,defAns);
        BW_threshold2=str2num(answer{1});
        smaller_object_size2=str2num(answer{2});
        shape_ratio2=str2num(answer{3});
        
        set(slider_seuil,'Value',BW_threshold2);
        set(slider_small,'Value',smaller_object_size2/typical_size);
        set(slider_rapport,'Value',shape_ratio2/typical_rapport);
    end
end