%%EditParamsKiloSort
% 12.01.2018 KJ
%
%  edit params.py generated by KiloSort and change the path of the data file
%
%
%INPUTS
% folder_params:        path to the folder of the params.py file
% folder_data:          path to the folder of the data file
%
%

function EditParamsKiloSort(folder_params,folder_data)

     if folder_data(end)~=filesep
         folder_data(end)=filesep;
     end
    
     old = 'dat_path = ''';
     new = ['dat_path = ''' folder_data];

     buffer = fileread(fullfile(folder_params, 'params.py')) ;
     buffer = strrep(buffer, old, new);
          
     fid = fopen(fullfile(folder_params, 'params.py'), 'w') ;
     fwrite(fid, buffer) ;
     fclose(fid) ;


end