function [fitresult, gof] = createFit_Sigmoid_Freezing(tps, dattemp,plo)
%CREATEFIT(TPS,DATTEMP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tps
%      Y Output: dattemp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Nov-2017 15:13:15


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tps, dattemp );

% Set up fittype and options.
ft = fittype( 'A/(1+exp(-b*(x-c)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1 1 0.5];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
if plo
% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
% Label axes
legend off
xlabel tps
ylabel dattemp
grid on
end

