clear all
stepsize = 2;
load(['/home/vador/Dropbox/Mobs_member/SophieBagur/Figures/BilnJan2019_OB4HzPaper/DataFzingStatesBBX_' num2str(stepsize),'.mat'])
% This data is generated by GenerateProbaTransitionsBBXMice_SB

figure

Vals = {DurActEp_SHAM(:,3);DurActEp_BBX(:,3)};
XPos = [1.1,1.9];
[h,p] = ranksum(Vals{1},Vals{2})

Cols = [0.9,1,0.9;0.9,0.9,1];
for k = 1:2
    X = Vals{k};
    a=iosr.statistics.boxPlot(XPos(k),X,'boxColor',Cols(k,:),'lineColor',Cols(k,:),'medianColor','k','boxWidth',0.5,'showOutliers',false);
    a.handles.upperWhiskers.Visible='off';a.handles.upperWhiskerTips.Visible='off';
    a.handles.lowerWhiskers.Visible='off';a.handles.lowerWhiskerTips.Visible='off';
    a.handles.medianLines.LineWidth = 5;
    
    handlesplot=plotSpread(X,'distributionColors',[0 0 0],'xValues',XPos(k),'spreadWidth',0.4); hold on;
    set(handlesplot{1},'MarkerSize',22)
    handlesplot=plotSpread(X,'distributionColors',Cols(k,:)*0.8,'xValues',XPos(k),'spreadWidth',0.4); hold on;
    set(handlesplot{1},'MarkerSize',12)

end 
xlim([0.5 2.4])
ylim([0 210])
set(gca,'FontSize',18,'XTick',XPos,'XTickLabel',{'SHAM','BBX'},'linewidth',1.5,'YTick',[0:25:200])
ylabel('Active bout duration (s)')


figure
Vals = {DurFzEp_SHAM(:,3);DurFzEp_BBX(:,3)};
XPos = [1.1,1.9];
[h,p] = ranksum(Vals{1},Vals{2})
Cols = [0.9,1,0.9;0.9,0.9,1];
for k = 1:2
    X = Vals{k};
    a=iosr.statistics.boxPlot(XPos(k),X,'boxColor',Cols(k,:),'lineColor',Cols(k,:),'medianColor','k','boxWidth',0.5,'showOutliers',false);
    a.handles.upperWhiskers.Visible='off';a.handles.upperWhiskerTips.Visible='off';
    a.handles.lowerWhiskers.Visible='off';a.handles.lowerWhiskerTips.Visible='off';
    a.handles.medianLines.LineWidth = 5;
    
    handlesplot=plotSpread(X,'distributionColors',[0 0 0],'xValues',XPos(k),'spreadWidth',0.4); hold on;
    set(handlesplot{1},'MarkerSize',22)
    handlesplot=plotSpread(X,'distributionColors',Cols(k,:)*0.8,'xValues',XPos(k),'spreadWidth',0.4); hold on;
    set(handlesplot{1},'MarkerSize',12)
    
end

xlim([0.5 2.4])
ylim([0 15])
set(gca,'FontSize',18,'XTick',XPos,'XTickLabel',{'SHAM','BBX'},'linewidth',1.5,'YTick',[0:5:30])
ylabel('Freezing bout duration (s)')


% %% modified by SB tp put in number of freezing bouts in 120s
% figure
% Vals = {FreqInit_SHAM(:,3)*121.18;FreqInit_BBX(:,3)*121.18};
% XPos = [1.1,1.9];
% [h,p] = ranksum(Vals{1},Vals{2})
% Cols = [0.9,1,0.9;0.9,0.9,1];
% for k = 1:2
%     X = Vals{k};
%     a=iosr.statistics.boxPlot(XPos(k),X,'boxColor',Cols(k,:),'lineColor',Cols(k,:),'medianColor','k','boxWidth',0.5,'showOutliers',false);
%     a.handles.upperWhiskers.Visible='off';a.handles.upperWhiskerTips.Visible='off';
%     a.handles.lowerWhiskers.Visible='off';a.handles.lowerWhiskerTips.Visible='off';
%     a.handles.medianLines.LineWidth = 5;
%     
%     handlesplot=plotSpread(X,'distributionColors',[0 0 0],'xValues',XPos(k),'spreadWidth',0.4); hold on;
%     set(handlesplot{1},'MarkerSize',22)
%     handlesplot=plotSpread(X,'distributionColors',Cols(k,:)*0.8,'xValues',XPos(k),'spreadWidth',0.4); hold on;
%     set(handlesplot{1},'MarkerSize',12)
%     
%     
% end
% 
% xlim([0.5 2.4])
% ylim([0 00.15]*121)
% set(gca,'FontSize',18,'XTick',XPos,'XTickLabel',{'SHAM','BBX'},'linewidth',1.5,'YTick',[0:5:15])
% ylabel('Number of freezing bouts')
% 


figure
for l = 3
    subplot(2,1,1)
    for k=1:size(DistribActEpisodes_SHAM,1)
        [Y,X]=hist(DistribActEpisodes_SHAM{k,l},[0:0.5:160]);
        plot(X,cumsum(Y)/sum(Y),'color',[0.4 0.8 0.4],'linewidth',1.5)
        Distrib_Act_SHAM{l}(k,:)=cumsum(Y)/sum(Y);
        hold on
    end
    
    for k=1:size(DistribActEpisodes_BBX,1)
        [Y,X]=hist(DistribActEpisodes_BBX{k,l},[0:0.5:160]);
        plot(X,cumsum(Y)/sum(Y),'color',[0.4 0.4 0.8],'linewidth',1.5)
        Distrib_Act_BBX{l}(k,:)=cumsum(Y)/sum(Y);
        hold on
    end
    
    
    subplot(2,1,2)
    
    
    for k=1:size(DistribFzEpisodes_SHAM,1)
        [Y,X]=hist(DistribFzEpisodes_SHAM{k,l},[0:0.5:160]);
        plot(X,cumsum(Y)/sum(Y),'color',[0.4 0.8 0.4],'linewidth',1.5)
        Distrib_Fz_SHAM{l}(k,:)=cumsum(Y)/sum(Y);
        hold on
    end
    
    for k=1:size(DistribFzEpisodes_BBX,1)
        [Y,X]=hist(DistribFzEpisodes_BBX{k,l},[0:0.5:160]);
        plot(X,cumsum(Y)/sum(Y),'color',[0.4 0.4 0.8],'linewidth',1.5)
        Distrib_Fz_BBX{l}(k,:)=cumsum(Y)/sum(Y);
        hold on
    end
end
