clear all
stepsize = 2;
load( [dropbox '/Mobs_member/SophieBagur/Figures/BilnJan2019_OB4HzPaper/DataFzingStatesBBX_' num2str(stepsize),'.mat'])
% This data is generated by GenerateProbaTransitionsBBXMice_SB

figure

Vals = {DurActEp_SHAM(:,3);DurActEp_BBX(:,3)};
XPos = [1.1,1.9];
[h,p] = ranksum(Vals{1},Vals{2})

Cols = [0.9,1,0.9;0.9,0.9,1];
for k = 1:2
    X = Vals{k};
    a=iosr.statistics.boxPlot(XPos(k),X,'boxColor',Cols(k,:),'lineColor',Cols(k,:),'medianColor','k','boxWidth',0.5,'showOutliers',false);
    a.handles.upperWhiskers.Visible='off';a.handles.upperWhiskerTips.Visible='off';
    a.handles.lowerWhiskers.Visible='off';a.handles.lowerWhiskerTips.Visible='off';
    a.handles.medianLines.LineWidth = 5;
    
    handlesplot=plotSpread(X,'distributionColors',[0 0 0],'xValues',XPos(k),'spreadWidth',0.4); hold on;
    set(handlesplot{1},'MarkerSize',22)
    handlesplot=plotSpread(X,'distributionColors',Cols(k,:)*0.8,'xValues',XPos(k),'spreadWidth',0.4); hold on;
    set(handlesplot{1},'MarkerSize',12)

end 
xlim([0.5 2.4])
ylim([0 210])
set(gca,'FontSize',18,'XTick',XPos,'XTickLabel',{'SHAM','BBX'},'linewidth',1.5,'YTick',[0:25:200])
ylabel('Active bout duration (s)')


figure
Vals = {DurFzEp_SHAM(:,3);DurFzEp_BBX(:,3)};
XPos = [1.1,1.9];
[h,p] = ranksum(Vals{1},Vals{2})
Cols = [0.9,1,0.9;0.9,0.9,1];
for k = 1:2
    X = Vals{k};
    a=iosr.statistics.boxPlot(XPos(k),X,'boxColor',Cols(k,:),'lineColor',Cols(k,:),'medianColor','k','boxWidth',0.5,'showOutliers',false);
    a.handles.upperWhiskers.Visible='off';a.handles.upperWhiskerTips.Visible='off';
    a.handles.lowerWhiskers.Visible='off';a.handles.lowerWhiskerTips.Visible='off';
    a.handles.medianLines.LineWidth = 5;
    
    handlesplot=plotSpread(X,'distributionColors',[0 0 0],'xValues',XPos(k),'spreadWidth',0.4); hold on;
    set(handlesplot{1},'MarkerSize',22)
    handlesplot=plotSpread(X,'distributionColors',Cols(k,:)*0.8,'xValues',XPos(k),'spreadWidth',0.4); hold on;
    set(handlesplot{1},'MarkerSize',12)
    
end

xlim([0.5 2.4])
ylim([0 15])
set(gca,'FontSize',18,'XTick',XPos,'XTickLabel',{'SHAM','BBX'},'linewidth',1.5,'YTick',[0:5:30])
ylabel('Freezing bout duration (s)')


% %% modified by SB tp put in number of freezing bouts in 120s
% figure
% Vals = {FreqInit_SHAM(:,3)*121.18;FreqInit_BBX(:,3)*121.18};
% XPos = [1.1,1.9];
% [h,p] = ranksum(Vals{1},Vals{2})
% Cols = [0.9,1,0.9;0.9,0.9,1];
% for k = 1:2
%     X = Vals{k};
%     a=iosr.statistics.boxPlot(XPos(k),X,'boxColor',Cols(k,:),'lineColor',Cols(k,:),'medianColor','k','boxWidth',0.5,'showOutliers',false);
%     a.handles.upperWhiskers.Visible='off';a.handles.upperWhiskerTips.Visible='off';
%     a.handles.lowerWhiskers.Visible='off';a.handles.lowerWhiskerTips.Visible='off';
%     a.handles.medianLines.LineWidth = 5;
%     
%     handlesplot=plotSpread(X,'distributionColors',[0 0 0],'xValues',XPos(k),'spreadWidth',0.4); hold on;
%     set(handlesplot{1},'MarkerSize',22)
%     handlesplot=plotSpread(X,'distributionColors',Cols(k,:)*0.8,'xValues',XPos(k),'spreadWidth',0.4); hold on;
%     set(handlesplot{1},'MarkerSize',12)
%     
%     
% end
% 
% xlim([0.5 2.4])
% ylim([0 00.15]*121)
% set(gca,'FontSize',18,'XTick',XPos,'XTickLabel',{'SHAM','BBX'},'linewidth',1.5,'YTick',[0:5:15])
% ylabel('Number of freezing bouts')
% 


figure
for l = 3
    subplot(2,1,1)
    for k=1:size(DistribActEpisodes_SHAM,1)
        [Y,X]=hist(DistribActEpisodes_SHAM{k,l},[0:0.5:160]);
        plot(X,cumsum(Y)/sum(Y),'color',[0.4 0.8 0.4],'linewidth',1.5)
        Distrib_Act_SHAM{l}(k,:)=cumsum(Y)/sum(Y);
        hold on
    end
    
    for k=1:size(DistribActEpisodes_BBX,1)
        [Y,X]=hist(DistribActEpisodes_BBX{k,l},[0:0.5:160]);
        plot(X,cumsum(Y)/sum(Y),'color',[0.4 0.4 0.8],'linewidth',1.5)
        Distrib_Act_BBX{l}(k,:)=cumsum(Y)/sum(Y);
        hold on
    end
    
    
    subplot(2,1,2)
    
    
    for k=1:size(DistribFzEpisodes_SHAM,1)
        [Y,X]=hist(DistribFzEpisodes_SHAM{k,l},[0:0.5:160]);
        plot(X,cumsum(Y)/sum(Y),'color',[0.4 0.8 0.4],'linewidth',1.5)
        Distrib_Fz_SHAM{l}(k,:)=cumsum(Y)/sum(Y);
        NumEvents_Fz_SHAM{l}(k) = length(DistribFzEpisodes_SHAM{k,l});
        hold on
    end
    
    for k=1:size(DistribFzEpisodes_BBX,1)
        [Y,X]=hist(DistribFzEpisodes_BBX{k,l},[0:0.5:160]);
        plot(X,cumsum(Y)/sum(Y),'color',[0.4 0.4 0.8],'linewidth',1.5)
        Distrib_Fz_BBX{l}(k,:)=cumsum(Y)/sum(Y);
        NumEvents_Fz_BBX{l}(k) = length(DistribFzEpisodes_BBX{k,l});
        hold on
    end
end



OnlyChangeMaintenance = 1;
    load([dropbox '/Mobs_member/SophieBagur/Figures/BehaviourOptoDurationEvents/SimulationFzOpto' num2str(stepsize),'.mat'])

if OnlyChangeMaintenance
l = 3
for k=1:size(DurFzEp_SHAM,1)
    ErrMat = (DurFzEp-DurFzEp_BBX(k,l)).^2+(DurActEp-DurActEp_BBX(k,l)).^2;
    ErrMat = naninterp(ErrMat);
    ErrMat = SmoothDec(ErrMat,2);
    val = min(min(ErrMat));
    [row,col] = find(ErrMat == val);
    RemRow_BBX(k) = row;
    RemCol_BBX(k) = col;
end


l = 3;
for k=1:size(DurFzEp_SHAM,1)
    ErrMat = (DurFzEp-DurFzEp_BBX(k,l)).^2+(DurActEp-DurActEp_BBX(k,l)).^2;
    ErrMat = naninterp(ErrMat);
    ErrMat = SmoothDec(ErrMat,2);
    val = min(min(ErrMat));
    [row,col] = find(ErrMat == val);
    FreqInit_BBX_model(k,l) = FreqInit(row,RemCol_BBX(k));
end
end

figure
Vals = {FreqInit_SHAM(:,3)*121.18;FreqInit_BBX(:,3)*121.18;FreqInit_BBX_model(:,3)*121.18};
XPos = [1.1,1.9,2.7];

Cols = [0.9,1,0.9;0.9,0.9,1;0.9,0.9,1];
for k = 1:3
    X = Vals{k};
    a=iosr.statistics.boxPlot(XPos(k),X,'boxColor',Cols(k,:),'lineColor',Cols(k,:),'medianColor','k','boxWidth',0.5,'showOutliers',false);
    a.handles.upperWhiskers.Visible='off';a.handles.upperWhiskerTips.Visible='off';
    a.handles.lowerWhiskers.Visible='off';a.handles.lowerWhiskerTips.Visible='off';
    a.handles.medianLines.LineWidth = 5;
    hold on
end
        plot([1.9,2.7],[Vals{2},Vals{3}],'color',[0.7 0.7 0.9],'linewidth',1.5);

for k = 1:3
    X = Vals{k};
    handlesplot=plotSpread(X,'distributionColors',[0 0 0],'xValues',XPos(k),'spreadWidth',0.4), hold on;
    set(handlesplot{1},'MarkerSize',22)
    handlesplot=plotSpread(X,'distributionColors',Cols(k,:)*0.8,'xValues',XPos(k),'spreadWidth',0.4), hold on;
    set(handlesplot{1},'MarkerSize',12)
    
    
end

xlim([0.5 3.3])
ylim([0 00.15]*121)
set(gca,'FontSize',18,'XTick',XPos,'XTickLabel',{'SHAM','BBX','BBX-model'},'linewidth',1.5,'YTick',[0:5:15])
ylabel('Number of freezing bouts')
