function  A= SPWModulation(A)


A = getResource(A, 'CortSpikeData');

A = getResource(A, 'SPW_s1');
A = getResource(A, 'SPW_s2');





A = registerResource(A, 'SPWModTotal', 'numeric', {'CortCellList',2}, ...
    'SPWModTotal', ...
    ['z(t)-score for the sharp wave modulation comparing firing at spw with firing 10s later ', ...
      'first columnis sleep 1 second coumn is sleep 2'], 1);

A = registerResource(A, 'PreSPWModTotal', 'numeric', {'CortCellList',2}, ...
    'preSPWModTotal', ...
    ['z(t)-score for the sharp wave modulation comparing firing frmo (700-200ms) before spw with firing 10s later ', ...
   'first columnis sleep 1 second coumn is sleep 2' ], 1);

A = registerResource(A, 'SPWModBlocks', 'cell', {'CortCellList',1}, ...
    'SPWModBlocks', ...
    ['z(t)-score for the sharp wave modulation comparing firing at spw with firing 10s later ', ...
    'in 5 min blocks in sleep 2'], 1);

A = registerResource(A, 'SPWModBlocks', 'cell', {'CortCellList',1}, ...
    'SPWModBlocks', ...
    ['z(t)-score for the sharp wave modulation comparing firing at spw with firing 10s later ', ...
    'in 5min blocks in sleep 2'], 1);