function cf_=createFitSigMoidNP(NPDUR)
%CREATEFIT Create plot of data sets and fits
%   CREATEFIT(NPDUR)
%   Creates a plot, similar to the plot in the main Curve Fitting Tool,
%   using the data that you provide as input.  You can
%   use this function with the same data you used with CFTOOL
%   or with different data.  You may want to edit the function to
%   customize the code and this help message.
%
%   Number of data sets:  1
%   Number of fits:  2

% Data from data set "NPDUR":
%     Y = NPDUR:
%     Unweighted

% Auto-generated by MATLAB on 28-Oct-2015 10:31:07

% Set up figure to receive data sets and fits
f_ = clf;
figure(f_);
set(f_,'Units','Pixels','Position',[644 317 674 473]);
% Line handles and text for the legend.
legh_ = [];
legt_ = {};
% Limits of the x-axis.
xlim_ = [Inf -Inf];
% Axes for the plot.
ax_ = axes;
set(ax_,'Units','normalized','OuterPosition',[0 0 1 1]);
set(ax_,'Box','on');
axes(ax_);
hold on;

% --- Plot data that was originally in data set "NPDUR"
x_1 = (1:numel(NPDUR))';
NPDUR = NPDUR(:);
h_ = line(x_1,NPDUR,'Parent',ax_,'Color',[0.333333 0 0.666667],...
    'LineStyle','none', 'LineWidth',1,...
    'Marker','.', 'MarkerSize',12);
xlim_(1) = min(xlim_(1),min(x_1));
xlim_(2) = max(xlim_(2),max(x_1));
legh_(end+1) = h_;
legt_{end+1} = 'NPDUR';

% Nudge axis limits beyond data limits
if all(isfinite(xlim_))
    xlim_ = xlim_ + [-1 1] * 0.01 * diff(xlim_);
    set(ax_,'XLim',xlim_)
else
    set(ax_, 'XLim',[0.94999999999999995559, 6.0499999999999998224]);
end

% --- Create fit "fit 1"
fo_ = fitoptions('method','NonlinearLeastSquares','Lower',[-1 -10   0],'Upper',[2 10  5]);
ok_ = isfinite(x_1) & isfinite(NPDUR);
if ~all( ok_ )
    warning( 'GenerateMFile:IgnoringNansAndInfs',...
        'Ignoring NaNs and Infs in data.' );
end
st_ = [1 5 3 ];
set(fo_,'Startpoint',st_);
ft_ = fittype('a./(1+exp((x-d)*c))',...
    'dependent',{'y'},'independent',{'x'},...
    'coefficients',{'a', 'c', 'd'});

% Fit this model using new data
cf_ = fit(x_1(ok_),NPDUR(ok_),ft_,fo_);
% Alternatively uncomment the following lines to use coefficients from the
% original fit. You can use this choice to plot the original fit against new
% data.
%    cv_ = { 0.68102628461402092697, 2.2569850700066691473, 3.6920022412337853979};
%    cf_ = cfit(ft_,cv_{:});

% Plot this fit
h_ = plot(cf_,'fit',0.95);
set(h_(1),'Color',[1 0 0],...
    'LineStyle','-', 'LineWidth',2,...
    'Marker','none', 'MarkerSize',6);
% Turn off legend created by plot method.
legend off;
% Store line handle and fit name for legend.
legh_(end+1) = h_(1);
legt_{end+1} = 'fit 1';

% --- Create fit "fit 1 copy 1"
fo_ = fitoptions('method','NonlinearLeastSquares','Lower',[-1 -10   0],'Upper',[2 10  5]);
ok_ = isfinite(x_1) & isfinite(NPDUR);
if ~all( ok_ )
    warning( 'GenerateMFile:IgnoringNansAndInfs',...
        'Ignoring NaNs and Infs in data.' );
end
st_ = [1 5 3 ];
set(fo_,'Startpoint',st_);
ft_ = fittype('a./(1+exp((x-d)*c))',...
    'dependent',{'y'},'independent',{'x'},...
    'coefficients',{'a', 'c', 'd'});

% Fit this model using new data
cf_ = fit(x_1(ok_),NPDUR(ok_),ft_,fo_);
% Alternatively uncomment the following lines to use coefficients from the
% original fit. You can use this choice to plot the original fit against new
% data.
%    cv_ = { 0.68102628461402092697, 2.2569850700066691473, 3.6920022412337853979};
%    cf_ = cfit(ft_,cv_{:});

% Plot this fit
h_ = plot(cf_,'fit',0.95);
set(h_(1),'Color',[0 0 1],...
    'LineStyle','-', 'LineWidth',2,...
    'Marker','none', 'MarkerSize',6);
% Turn off legend created by plot method.
legend off;
% Store line handle and fit name for legend.
legh_(end+1) = h_(1);
legt_{end+1} = 'fit 1 copy 1';

% --- Finished fitting and plotting data. Clean up.
hold off;
% Display legend
leginfo_ = {'Orientation', 'vertical', 'Location', 'NorthEast'};
h_ = legend(ax_,legh_,legt_,leginfo_{:});
set(h_,'Interpreter','none');
% Remove labels from x- and y-axes.
xlabel(ax_,'');
ylabel(ax_,'');
