% DROPBOX  Return root path of local Dropbox folder
%    PATH = DROPBOX() returns the path.
%    PATH = DROPBOX(RELATIVE) returns the full path to a file or folder
%    relative to the root Dropbox path.
%
% DROPBOX keeps track of the location of your Dropbox folder across
% different machines and operating systems. On first-time use, it asks the
% user to locate the local Dropbox folder through a GUI window. The m-file
% then updates itself to recognize different machines through their
% hostname, so that only one copy of the file is needed (that you can keep
% in your Dropbox). DROPBOX does not rely on MATLAB preferences so it is
% robust across MATLAB versions and after fresh installs.
%
% Because the file edits itself, user changes are not recommended; the name
% of the file can be changed, however.

% DO NOT EDIT THIS FILE %

function p = dropbox(varargin)

switch strtrim(evalc('system(''hostname'');'))
    % Start hostname cases
    case 'MobsEcolo'
        p = fullfile('/home/greta/Dropbox',varargin{:});
    case 'mobsrick-HP-Z440-Workstation'
        p = fullfile('/home/mobsrick/Dropbox',varargin{:});
    case 'Vador'
        p = fullfile('/home/vador/Dropbox',varargin{:});
    case 'mobsmorty-Lenovo-Product'
        p = fullfile('/home/mobsmorty/Dropbox',varargin{:});
    case 'mobschapeau'
        p = fullfile('/home/mobschapeau/Dropbox',varargin{:});
    case 'mobsjefferson-HP-Z440-Workstation'
        p = fullfile('/home/mobsjefferson/Dropbox',varargin{:});
    case 'mobs-SL'
        p = fullfile('/home/mobs/Dropbox',varargin{:});
    case 'mobsjunior'
        p = fullfile('/home/mobsjunior/Dropbox',varargin{:});
    case 'mobsgruffalo'
        p = fullfile('/home/gruffalo/Dropbox',varargin{:});
    case 'mobs-Thierry'
        p = fullfile('/home/mobs/Dropbox',varargin{:});
    case 'mobsrick-WS'
        p = fullfile('/home/mobsrick/Dropbox',varargin{:});
    case 'XPS137390-1-BB'
        p = fullfile('C:\Users\sbagur\Dropbox',varargin{:});
    case 'HPMobs2'
        p = fullfile('C:\Users\MobsHP\Dropbox',varargin{:});
    case 'Dmitris-Air'
        p = fullfile('/Users/bryzgalovdm/Dropbox',varargin{:});
    case 'DESKTOP-D2EUN3U'
        p = fullfile('C:\Users\samue\Dropbox',varargin{:});
    case 'hypatia'
        p = fullfile('/home/mobs/Dropbox/',varargin{:});
    case 'crates'
        p = fullfile('/home/mobs/Dropbox',varargin{:});
    case 'Laptop-Dell'
        p = fullfile('C:\Users\samue\Dropbox',varargin{:});
    case 'Arsenii-PC'
        p = fullfile('C:\Users\Arsenii Goriachenkov\Dropbox\',varargin{:});
        %         p = fullfile('C:\Users\Arsenii Goriachenkov\Dropbox\Kteam\PrgMatlab\Arsenii\',varargin{:});
    case 'mobsmorty'
        p = fullfile('/home/mobsmorty/Dropbox',varargin{:});
    case 'mobshamilton-HP-Z440-Workstation'
        p = fullfile('/home/mobshamilton/Dropbox',varargin{:});
    case 'DESKTOP-5O4QK29'
        p = fullfile('F:\test\1203_UMaze_211001_143434',varargin{:});
    case 'mobs-ThinkCentre-Edge72'
        p = fullfile('/media/nas4/ProjetEmbReact/Mouse688/20180209/ProjectEmbReact_M688_20180209_Habituation24HPre_PreDrug/Hab1',varargin{:});
    case 'hobbes'
        p = fullfile('/home/hobbes/Dropbox',varargin{:});
    case 'ratatouille'
        p = fullfile('/home/ratatouille/Dropbox',varargin{:});
    case 'MobsEcolo'
        p = fullfile('/media/nas7/ProjetEmbReact/Mouse1562',varargin{:});
    case 'pinky'
        p = fullfile('/home/pinky/Dropbox',varargin{:});
    case 'mouse'
        p = fullfile('/home/mickey/Dropbox/Mobs_member/Theotime De Charrin/Figures',varargin{:});
    case 'theodechrn'
        p = fullfile('/home/theodechrn/Dropbox/Mobs_member/Theotime De Charrin/Figures',varargin{:});
        %##%
        % End hostname cases
    otherwise
        dbdr = uigetdir(pwd,'Please locate your Dropbox folder.');
        if ~dbdr
            error('Dropbox:dropbox:folderNotFound',...
                'Your Dropbox folder could not be located.')
        end
        tempfile = tempname();
        thisfile = which(mfilename);
        fi = fopen(thisfile,'r');
        fo = fopen(tempfile,'wt');
        if fo<0
            error('Dropbox:dropbox:tempnameFailed',...
                'Could not write temporary file to %s.',tempfile);
        end
        while ~feof(fi)
            buffer = fgetl(fi);
            if strcmp(buffer,'%##%')
                thishost = strtrim(evalc('system(''hostname'');'));
                fprintf(fo,'    case ''%s''\n',thishost);
                fprintf(fo,'        p = fullfile(''%s'',varargin{:});\n',dbdr);
            end
            fprintf(fo,'%s\n',buffer);
        end
        fclose(fi);
        fclose(fo);
        [success errmsg errid] = movefile(tempfile,thisfile,'f');
        if ~success
            error(errid,errmsg);
        end
        fprintf('Host ''%s'' added to %s.m!\n',thishost,mfilename);
end
