TRUE = 1;
FALSE = 0;
NEITHER = 2;
GOOD = 1;
BAD = 0;
UGLY = 1;
S(1) = ...
struct('data_dir',fullfile('6429','6429_01'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',GOOD,'note','');
S(2) = ...
struct('data_dir',fullfile('6429','6429_02'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(3) = ...
struct('data_dir',fullfile('6429','6429_03'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(4) = ...
struct('data_dir',fullfile('6429','6429_04'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',0,'nepochs',5,'sleep_qual',BAD,'note','');
S(5) = ...
struct('data_dir',fullfile('6429','6429_05'),'pcorrect',2/10,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(6) = ...
struct('data_dir',fullfile('6429','6429_06'),'pcorrect',6/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(7) = ...
struct('data_dir',fullfile('6429','6429_07'),'pcorrect',5/9,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',GOOD,'note','');
S(8) = ...
struct('data_dir',fullfile('6429','6429_08'),'pcorrect',9/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','finally switched to curtain on probes');
S(9) = ...
struct('data_dir',fullfile('6429','6429_09'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(10)= ...
struct('data_dir',fullfile('6429','6429_10'),'pcorrect',nan,'isold',TRUE,...   
'isnovel',FALSE,'isdoor_reward',NEITHER,'iscut',FALSE,'bigfirst',9,'nepochs',1,'sleep_qual',0,'note','REM recording, not smsms');
S(11)= ...
struct('data_dir',fullfile('6436','6436_02'),'pcorrect',6/6,'isold',TRUE,...
'isnovel',TRUE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',0,'nepochs',5,'sleep_qual',GOOD,'note','');
S(12)= ...
struct('data_dir',fullfile('6436','6436_03'),'pcorrect',2/3,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(13)= ...
struct('data_dir',fullfile('6436','6436_04'),'pcorrect',6/9,'isold',TRUE,... 
'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(14)= ...
struct('data_dir',fullfile('6436','6436_05'),'pcorrect',4/4,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',1,'nepochs',5,'sleep_qual',GOOD,'note','');
S(15)= ...
struct('data_dir',fullfile('6436','6436_06'),'pcorrect',10/10,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(16)= ...
struct('data_dir',fullfile('6436','6436_07'),'pcorrect',5/10,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE, ...
'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(17)= ...
struct('data_dir',fullfile('6436','6436_08'),'pcorrect',8/10,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE,'bigfirst',0,'nepochs',5,'sleep_qual',GOOD,'note','');
S(18)= ...
struct('data_dir',fullfile('6436','6436_09'),'pcorrect',9/10,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',FALSE,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(19)= ...
struct('data_dir',fullfile('6436','6436_10'),'pcorrect',10/10,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(20)= ...
struct('data_dir',fullfile('6481','6481_01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(21)= ...
struct('data_dir',fullfile('6481','6481_02'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(22)= ...
struct('data_dir',fullfile('6481','6481_03'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(23)= ...
struct('data_dir',fullfile('6481','6481_04'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',9,'nepochs',5,'sleep_qual',BAD,'note','');
S(24)= ...
struct('data_dir',fullfile('6481','6481_05'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(25)= ...
struct('data_dir',fullfile('6481','6481_06'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(26)= ...
struct('data_dir',fullfile('6481','6481_07'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',9,'nepochs',5,'sleep_qual',GOOD,'note','');
S(27)= ...
struct('data_dir',fullfile('6481','6481_08'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(28)= ...
struct('data_dir',fullfile('6568','6568_01'),'pcorrect',9/10,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',GOOD,'note','');
S(29)= ...
struct('data_dir',fullfile('6568','6568_02'),'pcorrect',9/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(30)= ...
struct('data_dir',fullfile('6568','6568_03'),'pcorrect',10/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(31)= ...
struct('data_dir',fullfile('6568','6568_04'),'pcorrect',10/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ...
,'bigfirst',0,'nepochs',5,'sleep_qual',GOOD,'note','Out of control EV');
S(32)= ...
struct('data_dir',fullfile('6568','6568_05'),'pcorrect',0/10,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(33)= ...
struct('data_dir',fullfile('6568','6568_06'),'pcorrect',3/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(34)= ...
struct('data_dir',fullfile('6568','6568_07'),'pcorrect',6/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',UGLY,'note','');
S(35)= ...
struct('data_dir',fullfile('6568','6568_08'),'pcorrect',9/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(36)= ...
struct('data_dir',fullfile('6568','6568_09'),'pcorrect',9/10,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(37)= ...
struct('data_dir',fullfile('6568','6568_10'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',NEITHER,'iscut',FALSE,'bigfirst',9,'nepochs',1,'sleep_qual',0,'note','REM Sleep test not SMSMS');

S(38)= ...
struct('data_dir',fullfile('6610','6610_01'),'pcorrect',nan,'isold',TRUE,...
'isnovel',TRUE,'isdoor_reward',0,'iscut',TRUE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note','');
S(39)= ...
struct('data_dir',fullfile('6610','6610_02'),'pcorrect',nan,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note','');
S(40)= ...
struct('data_dir',fullfile('6610','6610_03'),'pcorrect',nan,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note','');
S(41)= ...
struct('data_dir',fullfile('6610','6610_04'),'pcorrect',nan,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note','');
S(42)= ...
struct('data_dir',fullfile('6610','6610_05'),'pcorrect',nan,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note','');
S(43)= ...
struct('data_dir',fullfile('6610','6610_06'),'pcorrect',nan,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note','');
S(44)= ...
struct('data_dir',fullfile('6610','6610_07'),'pcorrect',nan,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note','');
S(45)= ...
struct('data_dir',fullfile('6610','6610_08'),'pcorrect',nan,'isold',TRUE,...
'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note','');
% Redo.
S(46)= ...
struct('data_dir',fullfile('6594','6594_01'),'pcorrect',nan,'isold',FALSE,...
'isnovel',TRUE,'isdoor_reward',0,'iscut',TRUE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note','');
S(47)= ...
struct('data_dir',fullfile('6594','6594_02'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',0,'iscut',TRUE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note','');
S(48)= ...
struct('data_dir',fullfile('6594','6594_03'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note','');
S(49)= ...
struct('data_dir',fullfile('6594','6594_04'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note','');
S(50)= ...
struct('data_dir',fullfile('6594','6594_05'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note','');
S(51)= ...
struct('data_dir',fullfile('6594','6594_06'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note','');
S(52)= ...
struct('data_dir',fullfile('6594','6594_07'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note','');
S(53)= ...
struct('data_dir',fullfile('6594','6594_08'),'pcorrect',nan,'isold',FALSE,...
'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note','');





