function [fitresult, gof] = FitGabor(X, Y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : X
%      Y Output: Ys
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Dec-2016 00:22:16


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*(x^2))*cos(2*pi*x*d+e)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [3 2 mean(Y) 4 1];
opts.Lower=[0 0 mean(Y)*0.5 0 0];
opts.Upper=[Inf Inf abs(mean(Y)*2) 5 7];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Cannot display contour plot for curves.


