function Hd = entoFilt
%ENTOFILT Returns a discrete-time filter object

%
% M-File generated by MATLAB(R) 7.0 and the Signal Processing Toolbox 6.2.
%
% Generated on: 09-Jul-2005 12:20:41
%

% Chebyshev Type I Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fpass = 300;        % Passband Frequency
Fstop = 400;        % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = cheby1(h, 'MatchExactly', match);


% [EOF]
