% This is the list of
%   - the types of cameras we use in out setups
% If you are using some new and exciting technology add it
% ExpeInfo should only include elements from this nomenclature


%Possible cameras
CameraType = ...
    {'FLIR-IRCamera',...
    'LogitechWebcam',...
    'None',....
};