% This is the list of
%   - digital channel identities 
% If you are using your digital channels to encode different information
% add it here
% ExpeInfo should only include elements from this nomenclature


%Brain regions
DigInputName = ...
    {'ONOFF',... % when intan goes on and off
    'STIM',... % for PAG/MFB stim
    'CS+WN','CS+Tone','CS-WN','CS-Tone',... % for fear conditionning
    'DeltaTone',... % for the delta tone project
    'CAMERASYNC',...
    'Laser',...
    'Shock',... % for an electric shock
    'NaN',...
    'OdorON',...
    'OdorOFF',...
    'STIM2',...
    'PIEZO',...
    };