% This is the list of
%   - mouse strains we use 
% If you are using a different strain
% ExpeInfo should only include elements from this nomenclature


%Strain names
StrainName = ...
    {'C57BL/6J Rj',...
    'Gad2-IRES-Cre',...
    'DBA/2Rj',...
    'C3H/HeNRj',...
    'CRH-Cre',...
    'Ferret',...
    'SST-Cre',...
    'Trami-PV',...
    };