% This is the list of
%   - the rooms in which we make recordings
% If you are using a new type of recording environment add it
% ExpeInfo should only include elements from this nomenclature


%Possible environments
RecordingRoom = ...
    {'AnimalFacilitySleepRoom',...
    'G4112-Cervelet',...
    'G4112-Striatum',...
    'G4112-Bulbe',...
    'G4111-Soundproof box',...
    'G4111',...
    'LSP lab'};