% This is the list of
%   - the type of environments in which we put the mice to make recordings
% If you are using a new type of recording environment add it
% ExpeInfo should only include elements from this nomenclature


%Possible environments
RecordingBoxType = ...
    {'Homecage',...
    'UMaze1',...
    'UMaze2',...
    'UMaze3',...
    'UMaze4',...
    'EPM',...
    'NPXSetup_HeadFixed',...
    'ImetronicCondCage',...
    'Clean homecage',...
    'Other mouse''s homecage',...
    'Nosepoke box',...
    'Stereotaxic device',...
    'Plethysmograph'...
    'SmallOpenField',...
    'OdorBucket',...
    'ExchangeCage',...
    'MB2 booth',...
    'PiezoCage'};