% This is the list of
%   - viruses that we inject
% If you are using a new virus add if here here
% ExpeInfo should only include elements from this nomenclature


%Brain regions
VirusName = ...
    {'rAAV5/Ef1a-DIO-TS-EYFP',...
    'rAAV5/Ef1a-DIO-eYFP',...
    'rAAV5/Ef1a-DIO-hChR2(H134R)-eYFP',...
    'rAAV2/hSyn-eGFP',...
    'rAAV5/hSyn-mCherry',...
    'AAV5/Ef1-DIO-hChR2-EYFP',...
    'rAAV9/CAG-ChR2-GFP',...
    'rAAV9/CamK2-ChR2-mcherry',...
    'rAAV5/CamK2-ChR2-mcherry',...
    'rAAV2/hsyn-DIO-hM4D(Gi)-mCherry',...
    'rAAV2/hsyn-HA-hM4D(Gi)-IRES-mCitrine',...
    'rAAV9/Flex-ArchT-GFP',...
    'rAAV9/Flex-ArchT-GFP',...
    'rAAV9/CAG-ArchT-GFP',...
    'rAAV8/hSyn-jaws-KGC—GFP-ER2',...
    'rAAV2/hSyn-jaws-KGC-GFP-ER2',...
    'AAV5/CAG-GCaMP6s-WPRE.SV40',...
    'AAV5/CAG-Flex.GCaMP6f.WPRE.SV40',...
    'AAV5/CAG-GCaMP6s-WPRE.SV40',...
    'rAAV2/hsyn-DIO-hM4D(Gi)-mCherry',...
    'AAV5.Syn.CaMPARI.WPRE.SV40',...
    'CMV.CavCre'};
