function answer = get_lfp_directory(prompt,str2)
% Preferences Modal Menu

% Display Parameters
W = 100;
H = 8;
ftsize = 10;
panelColor = get(0,'DefaultUicontrolBackgroundColor');
% answer = cell(1,1);
answer = [];

% Creating Dialog Box
f2 = dialog('Units','characters',...
    'Position',[30 30 W H],...
    'HandleVisibility','callback',...
    'IntegerHandle','off',...
    'Renderer','painters',...
    'Toolbar','figure',...
    'NumberTitle','off',...
    'Name',prompt);

tab0 = uipanel('FontSize',ftsize,...
    'Units','characters',...
    'Position',[0 3 W H-3],...
    'Parent',f2);
pos = get(tab0,'Position');

% OK & CANCEL Buttons
okButton = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[W/4 .5 W/4 2],...
    'String','OK',...
    'Parent',f2);

cancelButton = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'Position',[W/2 .5 W/4 2],...
    'String','Cancel',...
    'Parent',f2);

set(okButton,'Callback',@okButton_callback);
set(cancelButton,'Callback', @cancelButton_callback);

    function cancelButton_callback(~,~)
        answer = [];
        close(f2);
    end

   function okButton_callback(~,~)
       answer{1} = e1.String;
       close(f2);
   end

    function getdirButton_callback(~,~,edit)
        edit.String = uigetdir();
    end

% SEED directory - Editable text
e1 = uicontrol('Style','edit',...
    'Units','characters',...
    'String',str2,...
    'Position',[2 pos(4)-2-1.5 W-16 2],...
    'TooltipString','SEED',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);
b1 = uicontrol('Style','pushbutton',...
    'Units','characters',...
    'String','Browse',...
    'Position',[W-14 pos(4)-2-1.5 13 2],...
    'TooltipString','Get Dir',...
    'BackgroundColor',panelColor,...
    'Parent',tab0);

set(b1,'Callback', {@getdirButton_callback,e1});

waitfor(f2);

end