set(0,'DefaultFigureWindowStyle','docked')

load('SleepScoring_OBGamma', 'REMEpochWiNoise', 'SWSEpochWiNoise', 'WakeWiNoise', 'SmoothGamma', 'SmoothTheta', 'Epoch');
REMEp  =mergeCloseIntervals(REMEpochWiNoise,1E4);
SWSEp = mergeCloseIntervals(SWSEpochWiNoise,1E4);
WakeEp =  mergeCloseIntervals(WakeWiNoise,1E4);

[Stim, StimREM, StimSWS, StimWake, Stimts] = FindOptoStim_MC;

% gamma and theta power : restrict to non-noisy epoch
SmoothGammaNew = Restrict(SmoothGamma,Epoch);
SmoothThetaNew = Restrict(SmoothTheta,Epoch);

% gamma and theta power : subsample to same bins
t = Range(SmoothThetaNew);
ti = t(5:1200:end);
SmoothGammaNew = (Restrict(SmoothGammaNew,ts(ti)));
SmoothThetaNew = (Restrict(SmoothThetaNew,ts(ti)));

% REM
SmoothThetaREM  =  (Restrict(SmoothThetaNew,REMEp));
SmoothGammaREM  =  Restrict(SmoothGammaNew,ts(Range(SmoothThetaREM)));
% SWS
SmoothThetaSWS  =  (Restrict(SmoothThetaNew,SWSEp));
SmoothGammaSWS = Restrict(SmoothGammaNew,ts(Range(SmoothThetaSWS)));
% Wake
SmoothThetaWake = (Restrict(SmoothThetaNew,WakeEp));
SmoothGammaWake = Restrict(SmoothGammaNew,ts(Range(SmoothThetaWake)));


%%%REM%%%%
%%REM + 10s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimREM))),log(Data(Restrict(SmoothTheta,StimREM))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimREM+10E4))),log(Data(Restrict(SmoothTheta,StimREM+10E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
%title('M1109 Sham 200923 StartStimREM+0s and StartStimREM+10s')
%title('M1109 Sham 200924 StartStimREM+0s and StartStimREM+10s')
%title('M1109 Opto 200925 StartStimREM+0s and StartStimREM+10s')
%title('M1076 Sham 200701 StartStimREM+0s and StartStimREM+10s')
%title('M1076 Opto 200702 StartStimREM+0s and StartStimREM+10s')
title('M1136 Opto 201210 StartStimREM+0s and StartStimREM+10s')


%%REM + 20s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimREM))),log(Data(Restrict(SmoothTheta,StimREM))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimREM+20E4))),log(Data(Restrict(SmoothTheta,StimREM+20E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
%title('M1109 Sham 200923 StartStimREM+0s and StartStimREM+20s')
%title('M1109 Sham 200924 StartStimREM+0s and StartStimREM+20s')
title('M1109 Opto 200925 StartStimREM+0s and StartStimREM+20s')
%title('M1076 Sham 200701 StartStimREM+0s and StartStimREM+20s')
%title('M1076 Opto 200702 StartStimREM+0s and StartStimREM+20s')
%title('M1136 Opto 201210 StartStimREM+0s and StartStimREM+20s')

%%REM + 30s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimREM))),log(Data(Restrict(SmoothTheta,StimREM))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimREM+30E4))),log(Data(Restrict(SmoothTheta,StimREM+30E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
%title('M1109 Sham 200923 StartStimREM+0s and StartStimREM+30s')
%title('M1109 Sham 200924 StartStimREM+0s and StartStimREM+30s')
%title('M1109 Opto 200925 StartStimREM+0s and StartStimREM+30s')
%title('M1076 Sham 200701 StartStimREM+0s and StartStimREM+30s')
%title('M1076 Opto 200702 StartStimREM+0s and StartStimREM+30s')
title('M1136 Opto 201210 StartStimREM+0s and StartStimREM+30s')

%%REM + 60s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimREM))),log(Data(Restrict(SmoothTheta,StimREM))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimREM+60E4))),log(Data(Restrict(SmoothTheta,StimREM+60E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
%title('M1109 Sham 200923 StartStimREM+0s and StartStimREM+60s')
%title('M1109 Sham 200924 StartStimREM+0s and StartStimREM+60s')
%title('M1109 Opto 200925 StartStimREM+0s and StartStimREM+60s')
title('M1076 Opto 200702 StartStimREM+0s and StartStimREM+60s')

%%REM + 90s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimREM))),log(Data(Restrict(SmoothTheta,StimREM))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimREM+90E4))),log(Data(Restrict(SmoothTheta,StimREM+90E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 200925 StartStimREM+0s and StartStimREM+90s')

%%REM + 120s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimREM))),log(Data(Restrict(SmoothTheta,StimREM))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimREM+120E4))),log(Data(Restrict(SmoothTheta,StimREM+120E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 200925 StartStimREM+0s and StartStimREM+120s')

%%%SWS%%%%
%%SWS + 10s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimREM))),log(Data(Restrict(SmoothTheta,StimREM))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimREM+10E4))),log(Data(Restrict(SmoothTheta,StimREM+10E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 Sham 200924 StartStimSWS+0s and StartStimSWS+10s')
%title('M1109 Opto 200925 StartStimSWS+0s and StartStimSWS+10s')

%%SWS + 20s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimSWS))),log(Data(Restrict(SmoothTheta,StimSWS))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimSWS+20E4))),log(Data(Restrict(SmoothTheta,StimSWS+20E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 200925 StartStimSWS+0s and StartStimSWS+20s')

%%SWS + 30s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimSWS))),log(Data(Restrict(SmoothTheta,StimSWS))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimSWS+30E4))),log(Data(Restrict(SmoothTheta,StimSWS+30E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 200925 StartStimSWS+0s and StartStimSWS+30s')

%%SWS + 60s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimSWS))),log(Data(Restrict(SmoothTheta,StimSWS))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimSWS+60E4))),log(Data(Restrict(SmoothTheta,StimSWS+60E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 200925 StartStimSWS+0s and StartStimSWS+60s')

%%Wake%%%
%%Wake + 10s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimWake))),log(Data(Restrict(SmoothTheta,StimWake))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimWake+10E4))),log(Data(Restrict(SmoothTheta,StimWake+10E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 Sham 200924 StartStimWake+0s and StartStimWake+10s')
%title('M1109 Opto 200925 StartStimWake+0s and StartStimWake+10s')

%%Wake + 20s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimWake))),log(Data(Restrict(SmoothTheta,StimWake))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimWake+20E4))),log(Data(Restrict(SmoothTheta,StimWake+20E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 200925 StartStimWake+0s and StartStimWake+20s')

%%Wake + 30s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimWake))),log(Data(Restrict(SmoothTheta,StimWake))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimWake+30E4))),log(Data(Restrict(SmoothTheta,StimWake+30E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 Sham 200924 StartStimWake+0s and StartStimWake+30s')
%title('M1109 Opto 200925 StartStimWake+0s and StartStimWake+30s')

%%Wake + 60s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimWake))),log(Data(Restrict(SmoothTheta,StimWake))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimWake+60E4))),log(Data(Restrict(SmoothTheta,StimWake+60E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 200925 StartStimWake+0s and StartStimWake+60s')

%%Wake + 90s
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',3);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',3);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',3);
plot(log(Data(Restrict(SmoothGamma,StimWake))),log(Data(Restrict(SmoothTheta,StimWake))),'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[1 1 1]);
plot(log(Data(Restrict(SmoothGamma,StimWake+90E4))),log(Data(Restrict(SmoothTheta,StimWake+90E4))),'MarkerFaceColor',[0 0 0],...
    'MarkerFaceColor',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);
xlabel('SmoothGamma')
ylabel('SmoothTheta')
title('M1109 200925 StartStimWake+0s and StartStimWake+90s')

%%
%% figure
figure, hold on,
plot(log(Data(SmoothGammaREM)),log(Data(SmoothThetaREM)),'g.','MarkerSize',1);
plot(log(Data(SmoothGammaSWS)),log(Data(SmoothThetaSWS)),'r.','MarkerSize',1);
plot(log(Data(SmoothGammaWake)),log(Data(SmoothThetaWake)),'b.','MarkerSize',1);

plot(log(Data(Restrict(SmoothGamma,StimREM))),log(Data(Restrict(SmoothTheta,StimREM))),'k*')
plot(log(Data(Restrict(SmoothGamma,StimREM+20e4))),log(Data(Restrict(SmoothTheta,StimREM+20e4))),'ko','linewidth',2)


x1 = log(Data(Restrict(SmoothGamma,StimREM)));
y1 = log(Data(Restrict(SmoothTheta,StimREM)));

x2 = log(Data(Restrict(SmoothGamma,StimREM+20e4)));
y2 = log(Data(Restrict(SmoothTheta,StimREM+20e4)));



for a=1:length(StimREM)
        plot([x1(a) x2(a)], [y1(a) y2(a)],'k-','LineWidth',2, 'color', [0 0 0])
annotation('arrows,[x1(a) x2(a)], [y1(a) y2(a)]')
end