function [fitresult, gof] = createFit_logitfunction(x, y)
%CREATEFIT(POS_PREDICTION_TRAIN,LINPOS_TRAIN_BALANCED)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Pos_Prediction_Train
%      Y Output: LinPos_train_balanced
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Apr-2024 11:47:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'b*(log(x./(1-x))) +a', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.901066202444592 0.382728808471544];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'LinPos_train_balanced vs. Pos_Prediction_Train', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel Pos_Prediction_Train
% ylabel LinPos_train_balanced
% grid on
% 

